version: "3.8"

services:
  app:
    # image: registry.gitlab.com/justinianus2001/detect-prescription:latest
    image: detect-prescription
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:${PORT} || exit 1z
      interval: 180s
      timeout: 10s
      retries: 5